### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by n0toose** [Kenny-Haworth/Harvest-Moon-2.0#27]
Hey, I checked out the project and I feel like it's pretty promising, but maybe it'd be a good idea to reconsider a name change like other open source game clones: https://osgameclones.com/

Additionally, keeping the name may cause trademark-related issues in the long-term future.

**Comment by Kenny-Haworth** [comment]
@AlwaysLivid 
Hey there, sorry for the late reply.

As of now, I don't plan on profiting from this project or further updating it. As it is open source, anyone is welcome to pick the project up and change the name to prevent copyright and trademark-related issues if they wish to further development. Besides just the name, all the music and sound effects are taken directly from _Innocent Life: A Futuristic Harvest Moon_, so those would need to be changed as well.

This was done as both a project in my game development class in college and a capstone project for my honors program, so it was much easier to call the game what it was (a Harvest Moon copy) and use their sound effects rather than finding or making my own.

**Comment by n0toose** [comment]
> As of now, I don't plan on profiting from this project or further updating it.
>
> This was done as both a project in my game development class in college and a capstone project for my honors program, so it was much easier to call the game what it was (a Harvest Moon copy) and use their sound effects rather than finding or making my own.

Oh, sorry @Kenny-Haworth. I made the issue 3 days after the latest commit, so I presumed that this project was something that would be maintained in the longer run.
