### ISSUE TITLE
What version of the Godot does the game use?

### ISSUE THREAD

**Issue by colorworlds** [Kenny-Haworth/Harvest-Moon-2.0#28]
I want to learn how to develop the game through this project, but I find I can't open it with the Godot v3.2.1.  So what version of the Godot does the project use?

**Comment by colorworlds** [comment]
I found out that my problem is not caused by the version.
I don't know the theory, but when I replace the contents of file `default_env.tres` with the automatically generated default contents, I can open the project normally.

#### Original content：
```
[gd_resource type="Environment" load_steps=2 format=2]
[sub_resource type="ProceduralSky" id=1]
radiance_size = 4
sky_top_color = Color( 0.0470588, 0.454902, 0.976471, 1 )
sky_horizon_color = Color( 0.556863, 0.823529, 0.909804, 1 )
sky_curve = 0.25
ground_bottom_color = Color( 0.101961, 0.145098, 0.188235, 1 )
ground_horizon_color = Color( 0.482353, 0.788235, 0.952941, 1 )
ground_curve = 0.01
sun_energy = 16.0
[resource]
background_mode = 2
background_sky = SubResource( 1 )
fog_height_min = 0.0
fog_height_max = 100.0
ssao_quality = 0
```

#### Automatically generated content(what I used now)：
```
[gd_resource type="Environment" load_steps=2 format=2]
[sub_resource type="ProceduralSky" id=1]
[resource]
background_mode = 2
background_sky = SubResource( 1 )
```


The case with me is that the window turns white and loses its response.
If other people have this problem,Maybe can try to solve it with this method.

**Comment by Kenny-Haworth** [comment]
@colorworlds The version of Godot this game was developed in is 3.0.6. You can discover this by downloading the corresponding game file for your OS from the release version, right clicking on the file to view properties, and navigating to the "Details" tab.

<img width="370" alt="Godot Version" src="https://user-images.githubusercontent.com/32252084/80294166-68c79b00-871b-11ea-93c7-e363d87246db.PNG">

Godot will additionally tell you if the project was made for a different version when attempting to edit it. Godot 3.2.1 should have given you such a warning.

The reason you were able to run my project by replacing the default_env.tres file with one from Godot 3.2.1 was because the default_env.tres uses a different format in Godot 3.2.1 than in Godot 3.0.6, but as you noted it does not solve all the issues.

If you want to run the project in Godot 3.2.1, this should be possible by importing it, accepting the warning that the project was created in a later version, and opening the project anyways. You'd likely end up with several errors you would need to debug but once you fix them, the project could then work on Godot 3.2.1.
