### ISSUE TITLE
the move is weird

### ISSUE THREAD

**Issue by Can202** [Kenny-Haworth/Harvest-Moon-2.0#30]
I love this game, it's fun, but it's a bit strange to move the player, I don't know why, but I think it must be that when he pressed two keys, I release one and quickly use another key, it doesn't move immediately.
And it's too fast, maybe it can be another key to run.

Thanks for reading me

**Comment by Kenny-Haworth** [comment]
Hey there @Can202,

I will do my best to break down your concerns and address them.

**1. When you release a movement key and quickly press another one, it doesn't move immediately.**

Yes! This is true. It's very similar to early Pokemon games in the sense that the world is created through tiles, and the player can only move from tile to tile. If you are in the middle of moving from one tile to another and you suddenly change direction, the player cannot change direction until they have reached the tile they are currently moving towards.

In fact, almost all games have uninterruptable actions like this, where when the player chooses to perform an action, some other actions are unable to be performed until the chosen action has finished. For example, in most FPS (first person shooter) games, if you choose to vault over cover you cannot fire your gun during the duration of the vaulting animation, and you cannot cancel the action either.

**2. The player moves too fast. Can't you add a "run" key and make walking the default speed?**

I considered this while developing the game. Ultimately, I decided it would be a near useless feature to include. Let me explain why.

This game was based on [Innocent Life: A Futuristic Harvest Moon](https://en.wikipedia.org/wiki/Innocent_Life:_A_Futuristic_Harvest_Moon). In that game, you indeed had the ability to both walk and run. But I never used the walking! Why? It was just too slow. There was no point walking anywhere when I could choose to run and get there three times faster. I played through the game start to finish maybe 10 times, but I _never_ used the walking feature.

Additionally, you're now requiring the player hold down an extra button (like shift) in order to run everywhere. This is such an annoying problem that many games that do offer a running key also have an "autorun" feature, because people are tired of holding down a key to run. It adds an unnecessary layer of complication to the player's movement that offers little benefit or meaningful increase to the quality of the game.

Well, what if you place a stamina bar on the player to limit their sprinting distance (like in Skyrim)? Wouldn't that make it more interactable and fun? No, because what purpose does that serve in this peaceful farming game? In action games like Skyrim, stamina bars add another resource the player must manage in order to be successful. If your stamina bar is too low, you could find yourself running out of energy to swing your sword in the middle of a battle, or unable to catch an enemy that is escaping, or unable to escape from a stronger enemy that is chasing you. The stamina bar is usually able to be increased or upgraded in these games by leveling up, but if all you do is drop points into stamina, you'll be too low on health, armor, attack, or any other stat you have to take into consideration.

In this game there are no battles, enemies, or leveling up, so introducing a stamina bar would only detract from the freedom and fun of the game.

**3. It's a bit strange to move the player**

I have noticed that the movement is not normalized. This means when you're pressing two keys at once, you're actually moving faster than had you been pressing only one key. This is a bug, and one I intend to fix at some point. I don't have an ETA on that at the moment, but I will be addressing it in the future. It's on my "to do" list!

Thanks for your comments @Can202, I hope you enjoyed the game. Let me know if you have any other questions or issues.

Kenny
